// Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ThunderUrlResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThunderUrlResponse{}

// ThunderUrlResponse The env-Thunder URL handle registered for an environment — either the caller-supplied value, the value the server generated when the caller left it blank, or (for an environment that predates this handle feature) a value reproducing its pre-existing hostname exactly. Unlike ThunderUrlRequest, this is NOT always a bare DNS label: a grandfathered environment's handle can contain a dot and exceed 63 characters (up to 80), so no pattern/length constraint is declared here — see thundersvc.LegacyThunderHandleLabel.
type ThunderUrlResponse struct {
	Handle string `json:"handle"`
}

// NewThunderUrlResponse instantiates a new ThunderUrlResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThunderUrlResponse(handle string) *ThunderUrlResponse {
	this := ThunderUrlResponse{}
	this.Handle = handle
	return &this
}

// NewThunderUrlResponseWithDefaults instantiates a new ThunderUrlResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThunderUrlResponseWithDefaults() *ThunderUrlResponse {
	this := ThunderUrlResponse{}
	return &this
}

// GetHandle returns the Handle field value
func (o *ThunderUrlResponse) GetHandle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Handle
}

// GetHandleOk returns a tuple with the Handle field value
// and a boolean to check if the value has been set.
func (o *ThunderUrlResponse) GetHandleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Handle, true
}

// SetHandle sets field value
func (o *ThunderUrlResponse) SetHandle(v string) {
	o.Handle = v
}

func (o ThunderUrlResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThunderUrlResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["handle"] = o.Handle
	return toSerialize, nil
}

type NullableThunderUrlResponse struct {
	value *ThunderUrlResponse
	isSet bool
}

func (v NullableThunderUrlResponse) Get() *ThunderUrlResponse {
	return v.value
}

func (v *NullableThunderUrlResponse) Set(val *ThunderUrlResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableThunderUrlResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableThunderUrlResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThunderUrlResponse(val *ThunderUrlResponse) *NullableThunderUrlResponse {
	return &NullableThunderUrlResponse{value: val, isSet: true}
}

func (v NullableThunderUrlResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThunderUrlResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
