name: 'Setup Helm Chart'
description: 'Setup Helm and update chart dependencies'
inputs:
  chart-path:
    description: 'Path to the Helm chart'
    required: true
  helm-version:
    description: 'Helm version to install'
    required: false
    default: '3.14.0'
runs:
  using: 'composite'
  steps:
    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: ${{ inputs.helm-version }}

    - name: Cache Helm chart dependencies
      id: helm-cache
      if: hashFiles(format('{0}/Chart.lock', inputs.chart-path)) != ''
      uses: actions/cache@v4
      with:
        path: ${{ inputs.chart-path }}/charts
        key: helm-charts-${{ hashFiles(format('{0}/Chart.lock', inputs.chart-path)) }}

    - name: Download chart dependencies
      if: steps.helm-cache.outputs.cache-hit != 'true' && hashFiles(format('{0}/Chart.lock', inputs.chart-path)) != ''
      shell: bash
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update
        helm dependency update "${{ inputs.chart-path }}"
