{{- if .Values.agentManagerService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-management-platform.agentManagerService.fullname" . }}-gateway-manager
  labels:
    {{- include "agent-management-platform.agentManagerService.labels" . | nindent 4 }}
  {{- with .Values.agentManagerService.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.agentManagerService.gatewayMgtService.type }}
  ports:
    - port: {{ .Values.agentManagerService.gatewayMgtService.port }}
      targetPort: {{ .Values.agentManagerService.gatewayMgtService.targetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "agent-management-platform.agentManagerService.selectorLabels" . | nindent 4 }}
{{- end }}
